spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
Spring:
  security:
    oauth2:
      resouceserver:
        jwt:
          issur-uri: http://localhost:9999/auth/realms/one
