version: '3'
services:
  keycloak:
    image: jboss/keycloak:7.0.0
    ports:
      - "9999:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/one-realm.json
    volumes:
      - "./realms:/tmp"
